### ISSUE TITLE
Fails when composer uses `symfony/console:^4`

### ISSUE THREAD

**Issue by weirdan** [zendframework/zend-expressive-skeleton#243] opened 2018-03-19 19:02 UTC
See composer/composer#7199

`z-e-s` calls [ConsoleIO::ask() with array argument](https://github.com/zendframework/zend-expressive-skeleton/blob/a50879bfeedcd563596e61eb08e62238467187dc/src/ExpressiveInstaller/OptionalPackages.php#L254), and that fails when composer uses `symfony/console:^4`

Steps to reproduce:
1. install composer as a global composer package
2. configure your $PATH to run that
3. update global `symfony/console` to ^4
3. run `composer create-project zendframework/zend-expressive-skeleton dir`

Expected:
No failures, installer asks what router/templater/di container to use

Actual:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given, called in /home/weirdan/.compose
r/vendor/composer/composer/src/Composer/IO/ConsoleIO.php on line 239 and defined in /home/weirdan/.composer/vendor/symfony/console/Question/Question.php:37
Stack trace:
#0 /home/weirdan/.composer/vendor/composer/composer/src/Composer/IO/ConsoleIO.php(239): Symfony\Component\Console\Question\Question->__construct(Array, '2')
#1 /home/weirdan/src/t/src/ExpressiveInstaller/OptionalPackages.php(254): Composer\IO\ConsoleIO->ask(Array, '2')
#2 /home/weirdan/src/t/src/ExpressiveInstaller/OptionalPackages.php(175): ExpressiveInstaller\OptionalPackages->requestInstallType()
#3 /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): ExpressiveInstaller\OptionalPackages::install(Object(Composer\Script\Event))
#4 /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatche in /home/weirdan/.composer/vendor/symfony/console/Question/Question.php on line 37

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given, called in /home/weirdan/.composer/vendor/composer/composer/src/Composer/IO/ConsoleIO.php on line 239 and defined in /home/weirdan/.composer/vendor/symfony/console/Question/Question.php:37
Stack trace:
#0 /home/weirdan/.composer/vendor/composer/composer/src/Composer/IO/ConsoleIO.php(239): Symfony\Component\Console\Question\Question->__construct(Array, '2')
#1 /home/weirdan/src/t/src/ExpressiveInstaller/OptionalPackages.php(254): Composer\IO\ConsoleIO->ask(Array, '2')
#2 /home/weirdan/src/t/src/ExpressiveInstaller/OptionalPackages.php(175): ExpressiveInstaller\OptionalPackages->requestInstallType()
#3 /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): ExpressiveInstaller\OptionalPackages::install(Object(Composer\Script\Event))
#4 /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatche in /home/weirdan/.composer/vendor/symfony/console/Question/Question.php on line 37
```

**Edit**: Current `composer.phar` that can be downloaded from getcomposer.org does not suffer from this issue. Apparently it uses older `symfony/console` package.

**Comment by weierophinney** [comment] 2018-03-19 19:04
Is this a common setup? I'm asking, because I've not encountered it before, and I'm wondering what percentage of users this may affect. (I'm worried that updating the installer may make it unusable for more people than it would fix issues for...)

Can you provide me a bit more context?

**Comment by weirdan** [comment] 2018-03-19 19:09
I don't have stats, it's just the way I always used composer: set up it from apt repo (as you imagine, always outdated) and then do `composer global require composer/composer` and use that.

Even if it's very exotic, the bug will manifest itself when `composer.phar` gets new `symfony/console` version (unless someone would fix it on composer's side).

**Comment by weierophinney** [comment] 2018-03-19 19:11
> set up it from apt repo (as you imagine, always outdated) and then do composer global require composer/composer and use that.

I have literally never seen it maintained that way; fascinating!

I'll have to check and see what happens when I get the update locally; haven't updated in a couple of months, so that may be why I've not seen the issues. I'll test, and then figure out what we need to do to address it.

Thanks for the report!

**Comment by xtreamwayz** [comment] 2018-03-21 07:01
I digged into the symfony/console history and it seems that the `$question` parameter always has been a string (according to the docblock). They only added a typehint for it in v4.

Composer itself is using v2: `Installing symfony/console (v2.8.32): Loading from cache`

**Comment by xtreamwayz** [comment] 2018-03-21 07:52
@weirdan This should be fixed with #243. Could you confirm please.

**Closed** 2018-03-21 16:46 UTC
Labels: bug

**Comment by weirdan** [comment] 2018-03-21 20:07
I can confirm 3.0.2 fixed this issue. Not sure how to point composer to alternative repository for `create-project` command. Does one just add alternative repository globally?

**Comment by xtreamwayz** [comment] 2018-03-21 20:12
I don't think that works actually. I have use a local setup to test changes locally:

https://gist.github.com/xtreamwayz/7590e55f95e98daf8d930b64cd8e4b69

**Comment by weierophinney** [comment] 2018-03-21 20:12
Not understanding the "alternative repository" question - why are you wanting to use one?

When it comes to using an alternate repository with `create-project`, the help composer provides is useful: `composer help create-project` indicates `--repository=URL` is what you need (and that needs to resolve to a composer repository or a `packages.json` file.

3.0.2 has already been released, and I've confirmed `create-project` picks it up...

**Comment by xtreamwayz** [comment] 2018-03-21 20:13
I think he means if he wants to test a specific branch or PR with changes.

**Comment by weierophinney** [comment] 2018-03-21 20:29
For testing branches, you can do so using typical constraint notation:

```bash
$ composer create-project "zendframework/zend-expressive-skeleton:dev-develop" project
```

Unfortunately, testing against a PR is not as easy, as PR branches typically exist on somebody else's repository. I've never yet found a way to do it solely via the CLI; when I've tested previously, I had to do a deep-dive into the `packages.json` format Composer expects for repositories, and write a JSON file that conformed and pointed to the repositories I was testing against.

**Comment by weirdan** [comment] 2018-03-21 20:35
>  testing against a PR is not as easy

Yep, that what my question was about, as @xtreamwayz asked to test the PR. For ordinary packages that would be easy, because there's a `composer.json` in a project folder where you can add alternative vcs repository, but template project packages (or whatever composer calls them) are obviously more tricky.

**Comment by xtreamwayz** [comment] 2018-03-21 20:43
The problem with `create-project` is that you cannot use a local copy with the `path` option. You always need to commit all changes before you test and use the branch as a reference.
