### ISSUE TITLE
composer serve & PHP 7.1.12

### ISSUE THREAD

**Issue by kevin2244** [zendframework/zend-expressive-skeleton#196] opened 2017-12-30 20:09 UTC
Hello.

There may be an issue with the composer.json since PHP version 7.1.12
due to the fix for  bug #75287 (see  https://bugs.php.net/bug.php?id=75287).

Running from the command line:

composer run --timeout=0 serve 

calls the inbuilt web server via this line in the composer.json:
"serve": "php -S 0.0.0.0:8080 -t public public/index.php",

This results in a fatal error as the path taken is now public/public/index.php

due to the router script (public/index.php in the composer.json) now being relative

to document root (public) due to the above fix. 

Changing the composer line to:
"serve": "php -S 0.0.0.0:8080 -t public index.php"

corrects the problem for PHP >=7.1.12

The problem is repeatable.

Kevin S

**Comment by xtreamwayz** [comment] 2018-01-01 10:40
We haven't found a solution that works on all platforms. But according to that link it isn't platform related but related to the PHP version.

> This not just fixed that bug, but also changed the way relative path to the router script is treated. Previously it assumed the path to be relative to $CWD, now it's relative to document root (set with the -t option).
>
>It caused (easily fixed) breaks for scripts that were starting CLI server like this: 
>  php -S 0.0.0.0:8888 -t public public/index.php. 
>
>Now they fail with:
>
>  PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
>  PHP Fatal error:  Unknown: Failed opening required '<path to>/public/public/index.php'
>
>(note the duplicate 'public/public').
>
>The fix is to start CLI server like this (router path is relative to doc root): 
>  php -S 0.0.0.0:8888 -t public index.php

Related #181, #190, #191.

**Comment by SharakPL** [comment] 2018-01-25 01:06
I can confirm the same happens with PHP 7.2.1 on Windows. Using `composer serve` where `"serve": "php -S 0.0.0.0:8080 -t public public/index.php"` at first makes server stop right after I try to open localhost:8080. The second time gives me fatal error because my public/index.php turnes into some kind of ghost file 😩 It's not there (only .htaccess, favicon.ico and zf-logo.png in public/) but I can't use another index.php in this directory, because access to this ghost file is forbidden.  Removing `public/` fixes the problem.

Shouldn't it be simply `php -S 0.0.0.0:8080 -t public/ index.php`?

**Comment by xtreamwayz** [comment] 2018-01-25 06:13
It seems that the bug was introduced in php-7.2.1, php-7.2.0, php-7.1.12, php-7.0.27, php-7.0.26: https://github.com/php/php-src/commit/816758eda2bcdd69ba505fb6bbb79124a7bf2254
And it is reverted back in php-7.2.2RC1, php-7.1.14RC1: https://github.com/php/php-src/commit/9e98e99a3a88f98d1377d5b2a43b7ad223d8a61f

Once I get the chance to test it in 7.1.14 or 7.2.2 and both in windows and linux, I'll make a new PR.

> Shouldn't it be simply php -S 0.0.0.0:8080 -t public/ index.php?

This is what I prefer and should work everywhere according to the docs. It also makes no sense to use `-t public public/index.php` as the `-t` argument already sets the root path.

**Comment by weierophinney** [comment] 2018-01-25 14:43
Just as a note: What we've found is that the built-in web server behaves differently based on OS. On Windows and MacOS, the form `php -S 0.0.0.0:8080 -t public/ index.php` works; on Linux, this needs to be `php -S 0.0.0.0:8080 -t public/ public/index.php`. Neither of those works with the other operating systems.

Glad to find you confirmed it was a bug in PHP, @xtreamwayz !

**Comment by xtreamwayz** [comment] 2018-02-07 12:25
Let's settle this once and for all ;)

This works for me on windows: 

- Windows PowerShell `php -S 0.0.0.0:8080 -t public/`
- Windows cmd `php -S 0.0.0.0:8080 -t public/`
- Windows WSL `php -S 0.0.0.0:8080 -t public/`

You need to test this on PHP 7.1.14 or PHP 7.2.2. Older versions had an issue with the internal server.
Can people confirm this works in linux distros please.

**Comment by weierophinney** [comment] 2018-02-07 15:11
Building 7.1.14 now, and will update once I've tested.

**Comment by webimpress** [comment] 2018-02-07 15:17
@xtreamwayz @weierophinney 
```console
$ php -S 0.0.0.0:8080 -t public/
```

works correctly on macOS (High Sierra 10.13.3, with default PHP version: now it's PHP 7.1.7).

**Comment by weierophinney** [comment] 2018-02-07 15:21
@webimpress — It's always worked on macOS; linux has been the outlier. That's why I'm compiling 7.1.14 to test against. :)

**Comment by weierophinney** [comment] 2018-02-07 15:24
@xtreamwayz CONFIRMED! Works fine now!

**Comment by webimpress** [comment] 2018-02-07 15:30
@xtreamwayz @weierophinney I've checked also on Ubuntu with PHP 7.1.13 and it works as well:

> PHP 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 13:26:45) ( NTS )

It means we are going to require PHP 7.1.13+ in composer? Or only note in the docs that inbuilt server works on these versions?

**Comment by weierophinney** [comment] 2018-02-07 15:32
> It means we are going to require PHP 7.1.13+ in composer? Or only note in the docs that inbuilt server works on these versions?

Note it in the docs, and indicate that previous versions may require the user to manually start the PHP built-in server on Linux hosts.

**Comment by xtreamwayz** [comment] 2018-02-08 11:07
Thank you for your feedback. This is fixed in #216.

**Comment by weierophinney** [comment] 2018-02-08 16:26
Fixed in #216.

**Closed by weierophinney** 2018-02-08 16:26 UTC
Labels: bug
